services:
  db:
    image: postgres:17.4-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prototype_base
    ports:
      - 5432:5432
volumes:
  db-data:
